// Generated by CoffeeScript 1.10.0
(function() {
  var backgroundImage, backgroundReady, canvas, ctx, drawKronos, keysDown, kronos, kronosImage, kronosReady, main, previous, render, requestAnimationFrame, score, update, w,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  canvas = document.getElementById("titanomachy");

  ctx = canvas.getContext("2d");

  backgroundReady = false;

  backgroundImage = new Image();

  backgroundImage.onload = function() {
    return backgroundReady = true;
  };

  backgroundImage.src = "images/background.jpg";

  kronos = {
    height: 80,
    width: 40,
    x: 0,
    y: 0,
    speed: 5
  };

  kronosReady = false;

  kronosImage = new Image();

  kronosImage.onload = function() {
    return kronosReady = true;
  };

  kronosImage.src = "images/kronos.jpg";

  drawKronos = function() {
    ctx.fillStyle = "rgba(255,255,255,1)";
    return ctx.fillRect(kronos.x, kronos.y, kronos.width, kronos.height);
  };

  score = 0;

  keysDown = [];

  addEventListener("keydown", function(e) {
    return keysDown[e.keyCode] = true;
  }, false);

  addEventListener("keyup", function(e) {
    return delete keysDown[e.keyCode];
  }, false);

  update = function(interval) {
    if (indexOf.call(keysDown, 37) >= 0) {
      kronos.x -= kronos.speed * interval;
    }
    if (indexOf.call(keysDown, 39) >= 0) {
      return kronos.x += kronos.speed * interval;
    }
  };

  render = function() {
    if (backgroundReady) {
      ctx.drawImage(backgroundImage, 0, 0);
    }
    if (kronosReady) {
      ctx.drawImage(kronosImage, 0, 0);
    }
    return drawKronos();
  };

  main = function() {
    var change, now, previous;
    now = Date.now();
    change = now - previous;
    render();
    update(change / 1000);
    previous = now;
    return requestAnimationFrame(main);
  };

  w = window;

  requestAnimationFrame = w.requestAnimationFrame || w.webkitRequestAnimationFrame || w.msRequestAnimationFrame || w.mozRequestAnimationFrame;

  previous = Date.now();

  main();

}).call(this);
